name: Build with gcc
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'choose a dtb'
        required: true
        default: "19771/sdmmagpie.dtb"
        options:
        - "19111/sdmmagpie.dtb"
        - "19771/sdmmagpie.dtb"
  push:
    branchs: "testing"

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-22.04
    steps:

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Set SWAP to 5GiB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Initialize compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install git automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3
          sudo apt install gcc-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
          mkdir -p $GITHUB_WORKSPACE/workdir
          cd $GITHUB_WORKSPACE/workdir
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV

      #- name: python2.7
      #  run: |
      #    sudo rm /bin/python
      #    sudo ln -s /bin/python2.7 /bin/python
          
      - name: Get GCC toolchain
        run: |
          git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b -b lineage-20.0 --depth=1 $GITHUB_WORKSPACE/workdir/gcc

      - name: Get Kernel souce
        run: |
          git clone --recursive https://github.com/$GITHUB_REPOSITORY/ -b ${{ steps.branch-names.outputs.current_branch }} --depth 1 $GITHUB_WORKSPACE/workdir/source

      - name: Build Kernel
        run: |
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
          export ARCH="arm64"
          export SUBARCH="arm64"
          export PATH="$GITHUB_WORKSPACE/workdir/gcc/bin/:$PATH"
          export CROSS_COMPILE="$GITHUB_WORKSPACE/workdir/gcc/bin/"
          export CROSS_COMPILE_ARM32="$GITHUB_WORKSPACE/workdir/gcc/bin/"
          cd $GITHUB_WORKSPACE/workdir/source
          make O=out X2_defconfig DTB_NAMES="${{ github.event.inputs.target }}"
          make -j$(nproc --all) O=out CC=clang++ GCC=clang++ LD=ld.lld

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: workdir/source/out/arch/arm64/boot/Image.gz-dtb
          
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: Image
          path: workdir/source/out/arch/arm64/boot/Image
